version: '3.8'

services:
  websocket-server:
    build:
      context: .
      dockerfile: ServerHP.WebSocketServer/Dockerfile
    ports:
      - "5287:5287"
    networks:
      - app-network

  grpc-server:
    build:
      context: .
      dockerfile: ServerHP.GrpcServer/Dockerfile
    ports:
      - "5024:5024"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ServerHP.Client/Dockerfile
    ports:
      - "5193:5193"
    depends_on:
      - websocket-server
      - grpc-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
